#
# Azure Pipeline - Build defintion for Dotnet Core Demo app (Linux & Windows)
# Build as Docker container image and push to ACR, also push to public Dockerhub
# Ben C, 2019
#
trigger: 
  branches:
    include: [ master ] 

variables:
  - group: shared-secrets
  - name: app-name
    value: dotnet-demoapp
  - name: acr-name
    value: bcdemo
  - name: dockerhub-name
    value: bencuk
    
jobs:
  # ==================================================================
  # Job 1 - Build Image using Alpine Linux
  # ==================================================================  
  - job: build_linux_image
    variables:
      - name: docker-file
        value: docker/Dockerfile  
    pool:
      name: Hosted Ubuntu 1604

    steps:
    #
    # Run Docker build
    #
    - bash: |
        docker build . -f $(docker-file) -t $(dockerhub-name)/$(app-name):latest -t $(acr-name).azurecr.io/apps/$(app-name):latest -t $(acr-name).azurecr.io/apps/$(app-name):$(Build.BuildNumber)
      displayName: 'Build app as container image'

    #
    # Push latest + tagged images to ACR
    #
    - bash: |
        docker login $(acr-name).azurecr.io -u $(acr-name) -p $(acr-password)
        docker push $(acr-name).azurecr.io/apps/$(app-name)
      displayName: 'Push image to ACR'

    #
    # Push latest to Dockerhub
    #
    - bash: |
        docker login -u $(dockerhub-name) -p $(dockerhub-password)
        docker push $(dockerhub-name)/$(app-name):latest
      displayName: 'Push image to Dockerhub'

  # ==================================================================
  # Job 2 - Build Image using Windows Nanoserver
  # ==================================================================
  - job: build_windows_image
    variables:
      - name: docker-file
        value: docker/nanoserver-sac2016.Dockerfile  
    pool:
      name: Hosted VS2017

    steps:
    #
    # Run Docker build
    #
    - bash: |
        docker build . -f $(docker-file) -t $(dockerhub-name)/$(app-name):windows -t $(acr-name).azurecr.io/apps/$(app-name):windows
      displayName: 'Build app as container image'

    #
    # Push latest + tagged images to ACR
    #
    - bash: |
        docker login $(acr-name).azurecr.io -u $(acr-name) -p $(acr-password)
        docker push $(acr-name).azurecr.io/apps/$(app-name):windows
      displayName: 'Push image to ACR'

    #
    # Push latest to Dockerhub
    #
    - bash: |
        docker login -u $(dockerhub-name) -p $(dockerhub-password)
        docker push $(dockerhub-name)/$(app-name):windows
      displayName: 'Push image to Dockerhub'      