FROM microsoft/aspnetcore-build:1.1.2
MAINTAINER Ben Coleman
WORKDIR /app

# Expose port 5000 on Kestrel webserver
EXPOSE 5000

# Copy whole project, remove any old binaries and run a restore 
COPY . .
RUN rm -rf obj/
RUN rm -rf bin/
RUN rm -rf pub/
RUN dotnet restore

# Build & publish
RUN dotnet publish --output pub --configuration Release
RUN touch pub/.insidedocker

# Run the published ASP.NET Core app
ENTRYPOINT ["dotnet", "pub/dotnet-demoapp.dll"] 
